export { userRoutes } from './user/user.routes'
export const userPath = '/users'
export { notesRoutes } from './notes/notes.router'
export const notesPath = '/notes'
export { labelRoutes } from './labels/labels.router'
export const labelPath = '/labels'